### ISSUE TITLE
key binding for helm-apropos

### ISSUE THREAD

**Issue by jasonblewis** [rodogi/emacs#1]
in your config.org you have this:

```
Let’s bind `C-f C-a` to helm-apropos

(global-set-key (kbd "C-x C-a") 'helm-apropos)
```
note the C-f C-a vs C-x C-a

**Comment by rodogi** [comment]
You are totally right, thanks for mentioning it.

**Comment by rodogi** [comment]
See commit 1f01ec14bb8a000befa686496aeece3b2f369eb1
